# Generated by Django 3.2.16 on 2022-12-30 10:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_of_event', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 12, 31, 10, 54, 38, 578630, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2025, 9, 25, 10, 54, 38, 578639, tzinfo=utc))])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_event'],
            },
        ),
    ]
