# Generated by Django 3.2.16 on 2022-12-30 11:04

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='money_required',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='need_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 12, 31, 11, 4, 0, 756576, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2025, 9, 25, 11, 4, 0, 756589, tzinfo=utc))]),
        ),
    ]
