# Generated by Django 3.2.16 on 2022-12-30 11:07

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221230_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 12, 31, 11, 7, 58, 873272, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2025, 9, 25, 11, 7, 58, 873282, tzinfo=utc))]),
        ),
    ]
