# Generated by Django 3.2.16 on 2023-02-19 14:03

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_date_of_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 20, 14, 3, 24, 100394, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2025, 11, 15, 14, 3, 24, 100403, tzinfo=utc))]),
        ),
    ]
