# Generated by Django 3.2.16 on 2023-02-19 14:17

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230219_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 20, 14, 17, 8, 317539, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2025, 11, 15, 14, 17, 8, 317548, tzinfo=utc))]),
        ),
    ]
