# Generated by Django 3.2.16 on 2022-12-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_auto_20221214_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(
                 on_delete=django.db.models.deletion.CASCADE,
                 to='tasks.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
