# Generated by Django 3.2.16 on 2022-12-14 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('due_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('state', models.CharField(
                    choices=[('CU', 'Current'), ('AC', 'Archived')],
                    default='CU', max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('priority', models.CharField(
                    choices=[('MUD', 'Must do'), ('MID', 'Might do'),
                             ('CAD', 'Can do')],
                    default='MUD', max_length=3)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state', '-date_created'],
            },
        ),
    ]
