# Generated by Django 3.2.16 on 2022-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Must do', 'Must do'), ('Might do', 'Might do'), ('Can do', 'Can do')], default='Must do', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Current', 'Current'), ('Archived', 'Archived')], default='Current', max_length=10),
        ),
    ]
